services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sabine-api-docker
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "4000:3001"